name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:

    - name: Run Hello World in Docker
      run: |
        apt update 
        apt install -y docker.io net-tools
        netstat --unix
        find /var/run
        ps ax
        env
        docker ps
        docker run --rm ubuntu:latest /bin/bash -c "echo Hello World"



