name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:

    - name: Run Hello World in Docker
      run: |
        sudo apt update 
        sudo apt install net-tools
        sudo netstat --unix
        sudo find /var/run
        ps ax
        env
        sudo docker ps
        docker run --rm ubuntu:latest /bin/bash -c "echo Hello World"



