name: AfterTest
run-name: AfterTest
on:
  workflow_run:
jobs:
  doit:
    # if: ${{ github.event.workflow_run.workflows == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "event=${{ toJson(github.event) }}"
