name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
  

    steps:

    - name: Run Hello World in Docker#
      
      run: |
        sudo apt update >> /dev/null
        sudo apt install -y curl dmidecode >> /dev/null
        sudo /usr/sbin/dmidecode -s system-manufacturer | tr "[:upper:]" "[:lower:]" | grep -q "microsoft corporation"



