name: AfterTest
run-name: AfterTest
on:
  workflow_run:
    workflows: [Test]
    types:
      - completed
jobs:
  doit:
    # if: ${{ github.event.workflow_run.workflows == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "event=${{ toJson(github.event) }}"
      - run: hostname
      - run: sudo grep -qa container=lxc /proc/1/environ
