name: Test
run-name: Test
on: [push]
jobs:
  job1:
    runs-on: [self-hosted]
    outputs:
      fancy: ${{steps.fancyoutput.outputs.out}}
      notfancy: ${{steps.notsofancyoutput.outputs.out}}
    steps:
      - id: fancyoutput
        run: echo "::set-output name=out::$( echo ${{secrets.DADA}} | head -c3)"
      - id: notsofancyoutput
        run: echo out=${{steps.fancyoutput.outputs.out}} >> $GITHUB_OUTPUT
      - run: hostname
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - id: test
        run: echo should "${{needs.job1.outputs.notfancy}}"
      - run: sudo dmidecode
      - run: sudo cat /proc/1/environ
      - run: sudo cat /proc/1/cgroup
      - run: sudo cat /proc/1/comm
      - run: uptime
      - run: ps -efww
