name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run Hello World in Docker
      run: |
        docker run --rm ubuntu:latest /bin/bash -c "echo Hello World"



