name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:

    - name: Run Hello World in Docker#
      env:
        DOCKER_SOCK: "unix:///var/run/docker.sock"
      run: |
        apt update 
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        apt-cache policy docker-ce
        apt install -y docker-ce net-tools
        netstat --unix
        find /var/run
        ps ax
        env
        docker ps
        docker run --rm ubuntu:latest /bin/bash -c "echo Hello World"



