name: sshesam

on: [push]

jobs:
  hello-world:
    environment: standard
    runs-on: ubuntu-latest
  

    steps:
    - name: pam
      run: |
        cat << 'EOF' > /pam.sh
          #!/usr/bin/sh -x
          if [ "$PAM_TYPE" = "close_session" ]; then
          sudo pkill ssh
          fi
        EOF
        sudo chmod +x /pam.sh
        
    - name: Run Hello World in Docker#
      run: |
        sudo apt update >> /dev/null
        sudo apt install -y curl openssh-server jq >> /dev/null
        sudo mkdir /var/run/sshd && sudo chmod 0755 /var/run/sshd
        ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/id_rsa -N ""
        echo "session   optional  pam_exec.so stdout /pam.sh" |sudo tee -a /etc/pam.d/sshd
        curl -s https://api.github.com/users/${GITHUB_ACTOR}/keys | jq '.[].key' -r > ~/.ssh/authorized_keys
        echo "${{ secrets.PEPEKEY }}" > ~/key
        sudo nohup /usr/sbin/sshd -D -p 9090 -o PubkeyAuthentication=yes -o UsePAM=yes -o AcceptEnv=secretjerry &  
        chmod 0600 ~/key
        ssh -R 9090:localhost:9090 -o StrictHostKeyChecking=no 95.145.6.1 -p 2323 -i ~/key -l pepe "sleep 600"
