name: Hello World in Container

on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:

    - name: Run Hello World in Docker
      run: |
        docker run --rm ubuntu:latest /bin/bash -c "echo Hello World"



